feature: Add Trabajos y estudios similares
RedBed24/data_mining_2425 pull request #8
Opened 2024-10-27 11:53 UTC by JavierLoro

Se añade tres estudios que exploran diferentes factores que afectan el rendimiento académico de estudiantes de secundaria. Estos estudios se centran en ayudar a entender cómo aspectos como el entorno familiar, las actividades extraescolares y el uso de herramientas tecnológicas pueden influir en el desempeño escolar.

2024-10-28 11:45 UTC, RedBed24 requested changes
Por favor, usa un linter y/o formatter.
Intenta que tu escritura sea constante.

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "Breve descripción, qué intentan resolver y para qué os pueden ser útiles estas ideas.\n",
```suggestion
    "<!-- Breve descripción, qué intentan resolver y para qué os pueden ser útiles estas ideas. -->\n",
```

No creo que se deba poner el enunciado del moodle en el trabajo.
Puedes comentarlo o quitarlo.

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "## Estudio A:\n",
```suggestion
    "### [Factors that affect the academic performance of high school students in the Sucúa-Ecuador canton](https://cienciadigital.org/revistacienciadigital2/index.php/CienciaDigital/article/view/2338)\n",
```

Usar un Título más descriptivo y enlazarlo con el original

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "## Estudio B: \n",
```suggestion
    "### [Family Dinner Frequency, Parent-Organised Informal Learning Activities, and Student Academic Performance: Evidence from Chinese Eighth-Grade Students](https://link.springer.com/article/10.1007/s40299-023-00759-5)\n",
```

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "## Estudio C:\n",
```suggestion
    "### [Predicting Secondary School Students' Academic Performance in Science Course by Machine Learning](https://eric.ed.gov/?q=students+academic+performance&id=EJ1415061)\n",
```

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "### Descripción del Estudio\n",
```suggestion
    "#### Descripción del Estudio\n",
```

Seguir correctamente la estructura de títulos

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "### Descripción del Artículo\n",
```suggestion
    "#### Descripción del Artículo\n",
```

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "**Objetivos del Estudio**:\n",
```suggestion
```

No repetir títulos

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "**Objetivos del Estudio**:\n",
```suggestion
    "#### Objetivos del Estudio\n",
```

Usar títulos consistentes

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "**Utilidad del Estudio**:  \n",
```suggestion
    "#### Utilidad del Estudio\n",
```

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "**Objetivos del Estudio**:\n",
```suggestion
    "#### Objetivos del Estudio\n",
```

2024-10-28 11:45 UTC, RedBed24 commented on trabajo.ipynb
> +    "**Utilidad del Estudio**:  \n",
```suggestion
    "#### Utilidad del Estudio\n",
```

2024-10-30 08:01 UTC, Sikander035 approved these changes

2024-10-30 08:05 UTC, merged